version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.sun.xml.ws:jaxws-tools"
        versions: ">= 3.0"
