version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.sun.xml.ws:jaxws-tools"
        versions: ">= 3.0"
  - package-ecosystem: "maven"
    directory: "/src/it/extension"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/test1"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.sun.xml.ws:jaxws-rt"
        versions: ">= 3.0"
  - package-ecosystem: "maven"
    directory: "/src/it/wsdlLocation"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.sun.xml.ws:jaxws-rt"
        versions: ">= 3.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
